name: "Github Action - Contributify"

on: 
  #push:
   # branches: 
    #  - master
    #  - first-action
  pull_request:
    branches: 
      - master
    types: [open,synchronize]

jobs:
  contributify_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install node'
        uses: actions/setup-node@v1
      
      - name: 'Install NPM depencencies'
        run: npm install
      - name: "Run code and check for CONTRIBUTORS.md file"
        run: node sol1.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
