name: "Contributify BOT (Github Action)"

on: 
  pull_request:
    branches: 
      - master
    types: [open,synchronize, closed]

jobs:
  contributify_bot:
    runs-on: ubuntu-latest
    steps:
    - name: 'Install node'
      uses: r4pt0s/contributify@master
    - name: Run bot  
      run: node dist/index.js
        
